/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-settings-panel-mixin.html
 */

/// <reference path="../polymer/types/lib/utils/mixin.d.ts" />

declare namespace ArcComponents {


  /**
   * Components implementing this mixin are part of ARC settings panel.
   * After mixing it into the prototype the component gain access to common
   * methods to read and update application settings.
   *
   * The element should override two methods: `_processValues()` and
   * `_setSettings()`. Process values shouls process incomming data and set
   * defaults and proper data types (application storage may not respect data
   * types!). When this function is not provided the element will use data as they
   * arrive from settings provider. The `_setSettings()` function should be used
   * to set appropieate settings on the UI.
   */
  function ArcSettingsPanelMixin<T extends new (...args: any[]) => {}>(base: T): T & ArcSettingsPanelMixinConstructor;

  interface ArcSettingsPanelMixinConstructor {
    new(...args: any[]): ArcSettingsPanelMixin;
  }

  interface ArcSettingsPanelMixin {

    /**
     * When set the element will not request current settings state and
     * will wait until it's properties are set.
     */
    manual: boolean|null|undefined;

    /**
     * When set the settings are baing loaded.
     */
    readonly loading: boolean|null|undefined;

    /**
     * Some panels have sub pages. This tracks selected page.
     */
    page: number|null|undefined;
    connectedCallback(): void;

    /**
     * Dispatches `settings-read` custom event to settings provider to read
     * application settings and sets received values on the component.
     *
     * @returns Promise resolved when operartion ends.
     */
    loadSettings(): Promise<any>|null;
    _readSettings(): any;
    _processValues(values: any): any;
    _setSettings(): void;

    /**
     * Dispatches `settings-changed` to settings provider with new value.
     *
     * @param key Setting key
     * @param value Value to store. Values are serialized.
     * @returns Promise resolved when settings are stored.
     */
    updateSetting(key: String|null, value: any|null): Promise<any>|null;

    /**
     * Returns a boolean value for the `value`.
     */
    _boolValue(value: any|null): Boolean|null;

    /**
     * Returns a numeric value for the `value`
     *
     * @param val Current value
     * @returns Translated value
     */
    _numValue(val: any|null): Number|null;

    /**
     * Shows internal sub-page
     */
    _showPage(e: ClickEvent|null): void;

    /**
     * Restores the main page of the editor.
     */
    back(): void;

    /**
     * To be used when a list item has a toggle button.
     * When clicking on the list option this function should be called to
     * toggle the button.
     */
    _toggleOption(e: ClickEvent|null): void;

    /**
     * Cancels the event and it's propagation.
     */
    _cancelEvent(e: Event|null): void;

    /**
     * Opens a URL in new window.
     * If the application handle `open-external-url` then it does nothing.
     */
    _openLink(url: String|null): void;
  }
}
